// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA_CaqNatLyRAtpVNU3VHpfOafYAmhKX0',
    appId: '1:480355601723:web:490e59340a3f547e327b1e',
    messagingSenderId: '480355601723',
    projectId: 'outfit-planner-7485e',
    authDomain: 'outfit-planner-7485e.firebaseapp.com',
    storageBucket: 'outfit-planner-7485e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdZK8qtcOvhlodnkC-pMOrcFGmQh4gm2E',
    appId: '1:480355601723:android:7334be825cd0a930327b1e',
    messagingSenderId: '480355601723',
    projectId: 'outfit-planner-7485e',
    storageBucket: 'outfit-planner-7485e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChi2rFJOh7-om4yQDoPdId4Vis2x2wTqU',
    appId: '1:480355601723:ios:d1159c14216cf411327b1e',
    messagingSenderId: '480355601723',
    projectId: 'outfit-planner-7485e',
    storageBucket: 'outfit-planner-7485e.firebasestorage.app',
    iosBundleId: 'com.s1t1.stylesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChi2rFJOh7-om4yQDoPdId4Vis2x2wTqU',
    appId: '1:480355601723:ios:d1159c14216cf411327b1e',
    messagingSenderId: '480355601723',
    projectId: 'outfit-planner-7485e',
    storageBucket: 'outfit-planner-7485e.firebasestorage.app',
    iosBundleId: 'com.s1t1.stylesync',
  );

}